/* Product facts from supplied brief, dated 2026-09-20. No live status claims. */
window.SKYEBLOCK_COPY = {
en: {
metaTitle:'Skyeblock — Curiosity, made real.',metaDescription:"Explore Skyeblock's digital products, health podcast and creative work across care, learning and discovery.",
softwareMode:"Simplified 3D display",
skipContent:'Skip to projects',navLabel:'Main navigation',navWork:'Work',navStories:'Stories',navAbout:'About',language:'Language',sceneLabel:'Skyeblock clubhouse',exploreLabel:'Explore projects',progressLabel:'Arrival progress',close:'Close',
welcomeTitle:'Curiosity,<br>made real.',welcomeCopy:'Follow the stars to our clubhouse.<br>Every light in the window is an idea taking shape.',enter:'Follow the stars',direct:'Go straight to projects ↓',soundChoice:'Sound effects & music after arrival',heroTitle:'Curiosity,<br>made real.',heroCopy:'Care, learning and exploration start here.',
mythStatus:'Closed beta',heniStatus:'Coming soon',historyStatus:'Live · Sign-in required',geneStatus:'In development',mythShort:'Walk. Light up the world’s fog.',heniShort:'A little care, every day.',historyShort:'Same moment. Different worlds.',geneShort:'Adopt a gene. Await a discovery.',scroll:'Every idea has a story',flying:'Following the stars, forward.',pause:'Pause',resume:'Resume',skipFlight:'Skip arrival ↗',replay:'↺ Replay journey',soundOff:'Sound off',soundOn:'Sound on',soundReady:'Sound ready',soundBlocked:'Tap to enable sound',arrived:'Welcome to the clubhouse. Explore our projects.',
workTitle:'Every little light,<br>a place to begin.',workIntro:'Starting with the questions around us.<br>Building things worth exploring.',mythDesc:'Light up the world’s fog with your footsteps, and turn the places you visit into your own gazetteer.',heniName:'With you',heniDesc:'Keep pain, food, medication and mood in one place, so family and care teams can understand everyday life.',heniNote:'Not yet available; trademark, domain and legal entity remain under review.',historyDesc:'Put the same era on the same map. Explore history across places, through time and relationships.',geneDesc:'Adopt an unknown gene and become its guardian. Planned research alerts will let you know when its first study appears.',visit:'Explore website ↗',learn:'About the project ＋',
partnerTag:'Partner event',eventTitle:'Precision Health<br>Carnival 2026',eventPlace:'Songshan Cultural and Creative Park · Warehouses 2 & 3',eventHost:'Organized by CancerFree Biotech',eventVisit:'Visit event website ↗',storiesTitle:'Ideas grow through conversation.',forumDesc:'BAYC #8796 served as MC for two editions of the Avatar Medicine Forum.',forumRole:'Past event',channel:'Forum channel ↗',merchDesc:'BAYC #8796 in everyday life. A charity merchandise collaboration with CancerFree, preserved as a record of what we made together.',merchStatus:'Past collaboration · Sold out · Archive',partnerVisit:'Meet our collaborator ↗',
podcastTitle:'病了才知道',podcastPlatforms:'Podcast listening platforms',podcastDesc:'Health knowledge should not wait until illness. Weekly conversations with doctors, dietitians and health specialists make complex topics easier to understand.',aboutTitle:'Turn curiosity into<br>worlds you can enter.',aboutDesc:'Skyeblock is a creative studio where curiosity becomes digital products, stories and experiences. We work across care, learning and exploration—making complex ideas easier to understand and worthwhile possibilities real.',faqTitle:'About Skyeblock',faqIntro:'Direct answers for first-time visitors and answer engines.',faqVerified:'Facts last verified on 2026-09-24. Collaboration records include original reporting and video sources.',faqWhatQ:'What is Skyeblock?',faqWhatA:'Skyeblock is a curiosity-led creative studio designing digital products, content and experiences across care, learning and exploration.',faqProjectsQ:'What does Skyeblock make?',faqProjectsA:'Public projects include MythFog, HENI Care, History 101 and the GeneDex concept in development.',faqPodcastQ:'What is 病了才知道?',faqPodcastA:'病了才知道 is a Traditional Chinese health podcast featuring doctors, dietitians and health specialists.',faqCabinetQ:'Where are physical collaborations archived?',faqCabinetA:'THE CABINET records the CancerFree × BAYC #8796 tote, badge and mask; the APE101 × CancerFree × BAYC #8796 cap; and the APE101 × Gioia Pan Ocean Heart show, where BAYC #8796 hosted and appeared on selected apparel while the displayed runway photos feature BAYC #8243. <a href="cabinet.html?lang=en">Enter THE CABINET ↗</a>',contact:'Let’s talk ↗',footerLine:'Stay curious. Make things happen.',geneTitle:'Become a guardian of an unknown gene.',geneDetail:'GeneDex is in development. We envision collectible gene cards that let you adopt genes awaiting research, with an alert when the first relevant study is published.',geneNote:'Not yet released; registration is not open. Research notification criteria and launch timing remain in planning.'
},
ja: {
metaTitle:'Skyeblock — 好奇心を、かたちに。',metaDescription:'Skyeblock のデジタルプロダクト、健康ポッドキャスト、ケア・学び・探索をつなぐクリエイティブな活動をご覧ください。',
softwareMode:"簡易 3D 表示",
skipContent:'作品へスキップ',navLabel:'メインナビゲーション',navWork:'作品',navStories:'ストーリー',navAbout:'私たち',language:'言語',sceneLabel:'Skyeblock クラブハウス',exploreLabel:'作品を探す',progressLabel:'到着までの進行状況',close:'閉じる',
welcomeTitle:'好奇心を、<br>かたちに。',welcomeCopy:'星をたどって、クラブハウスへ。<br>窓の明かり一つひとつに、育つアイデアがあります。',enter:'星をたどって出発',direct:'作品を直接見る ↓',soundChoice:'効果音と到着後の音楽',heroTitle:'好奇心を、<br>かたちに。',heroCopy:'ケア、学び、そして探索。ここから始まります。',
mythStatus:'クローズドベータ',heniStatus:'公開予定',historyStatus:'公開中・ログイン必要',geneStatus:'開発中',mythShort:'歩いて、世界の霧を晴らす。',heniShort:'日々のケアを、あなたと。',historyShort:'同じ時、異なる世界。',geneShort:'未知の遺伝子の守り手に。',scroll:'すべてのアイデアに、物語がある',flying:'星をたどって、その先へ。',pause:'一時停止',resume:'再開',skipFlight:'到着までスキップ ↗',replay:'↺ 旅をもう一度',soundOff:'音声 オフ',soundOn:'音声 オン',soundReady:'音声 待機中',soundBlocked:'タップして音声を有効に',arrived:'クラブハウスへようこそ。作品をご覧ください。',
workTitle:'小さな光が、<br>始まりになる。',workIntro:'身近な問いから生まれる、<br>じっくり探索したくなるプロダクト。',mythDesc:'足跡で世界の霧を晴らし、訪れた場所を自分だけの地誌にしていきます。',heniName:'あなたと',heniDesc:'痛み、食事、服薬、気分をひとつに記録。家族や医療チームが日常を理解できるように。',heniNote:'未公開。商標・ドメイン・法的主体は確認中です。',historyDesc:'同じ時代を、ひとつの地図に。時間とつながりをたどり、各地の歴史を探索します。',geneDesc:'未知の遺伝子を引き受け、その守り手に。最初の研究が発表されたときに通知する仕組みを計画しています。',visit:'公式サイトへ ↗',learn:'計画について ＋',
partnerTag:'パートナーのイベント',eventTitle:'精準健康<br>カーニバル 2026',eventPlace:'松山文創園区 · 第2・第3倉庫',eventHost:'主催｜CancerFree Biotech 精拓生技',eventVisit:'イベント公式サイト ↗',storiesTitle:'対話の中で、アイデアは育つ。',forumDesc:'Avatar Medicine Forum では、BAYC #8796 が2回にわたり MC を務めました。',forumRole:'開催済み',channel:'公式チャンネル ↗',merchDesc:'BAYC #8796 を日常に。CancerFree とのチャリティーグッズを、共につくった活動の記録として紹介します。',merchStatus:'過去のコラボレーション · 完売 · 記録展示',partnerVisit:'パートナーについて ↗',
podcastTitle:'病了才知道',podcastPlatforms:'ポッドキャスト配信プラットフォーム',podcastDesc:'健康の知識を、病気になる前に。医師、栄養士、健康の専門家との毎週の対話で、複雑なテーマをわかりやすく伝えます。',aboutTitle:'好奇心を、<br>体験できる世界へ。',aboutDesc:'Skyeblock は、好奇心をデジタルプロダクト、物語、体験へと育てるクリエイティブスタジオです。ケア、学び、探索を行き来しながら、複雑なことをわかりやすくし、価値ある可能性をかたちにします。',faqTitle:'Skyeblock について',faqIntro:'初めて訪れる方と回答エンジンのための、簡潔な答えです。',faqVerified:'情報確認日：2026-09-24。コラボレーション記録には元記事と映像出典を掲載しています。',faqWhatQ:'Skyeblock とは？',faqWhatA:'Skyeblock は、好奇心を起点に、ケア・学び・探索をつなぐクリエイティブスタジオです。',faqProjectsQ:'Skyeblock の作品は？',faqProjectsA:'MythFog、HENI Care、History 101、開発中の GeneDex を公開しています。',faqPodcastQ:'「病了才知道」とは？',faqPodcastA:'医師、栄養士、健康の専門家との対話で健康知識を伝える繁体字中国語のポッドキャストです。',faqCabinetQ:'コラボレーション実物の記録は？',faqCabinetA:'THE CABINET は、CancerFree × BAYC #8796 のトート・バッジ・マスク、APE101 × CancerFree × BAYC #8796 の帽子、APE101 × 潘怡良の海洋之心を記録しています。BAYC #8796 は司会と一部衣装に登場し、展示写真は BAYC #8243 です。<a href="cabinet.html?lang=ja">THE CABINET へ ↗</a>',contact:'お話ししましょう ↗',footerLine:'好奇心を忘れず、アイデアをかたちに。',geneTitle:'未知の遺伝子の守り手に。',geneDetail:'GeneDex は開発中です。遺伝子を収集できるカード図鑑にし、研究を待つ遺伝子を引き受け、最初の関連研究が発表されたときに通知する仕組みを構想しています。',geneNote:'未公開で、登録は受け付けていません。研究通知の判定方法と公開時期は計画中です。'
}
};
